---
- name: config | Configuring Kea DHCP
  ansible.builtin.template:
    src: "{{ item + '.j2' }}"
    dest: "{{ '/' + item }}"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart kea-dhcp
  become: true
  loop:
    - etc/kea/kea-dhcp-ddns.conf
    - etc/kea/kea-dhcp4.conf
