---
- name: debian | Installing Pre-Reqs
  ansible.builtin.apt:
    name: "{{ kea_dhcp_pre_reqs }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | Adding Kea DHCP Repo Key
  ansible.builtin.apt_key:
    url: "{{ kea_dhcp_repo_key }}"
    state: present
  become: true

- name: debian | Adding Kea DHCP Repo
  ansible.builtin.apt_repository:
    repo: "{{ kea_dhcp_repo }}"
    state: present
  become: true

- name: debian | Installing Kea DHCP Packages
  ansible.builtin.apt:
    name: "{{ kea_dhcp_packages }}"
    state: present
  become: true
  register: result
  until: result is successful
