---
# tasks file for ansible-kea-dhcp
- name: Set facts
  ansible.builtin.include_tasks: set_facts.yml

- name: Include Debian tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Include RedHat tasks
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Include SUSE tasks
  ansible.builtin.include_tasks: suse.yml
  when: ansible_os_family == "Suse"

- name: Include services tasks
  ansible.builtin.include_tasks: services.yml

- name: Include config tasks
  ansible.builtin.include_tasks: config.yml
  when: kea_dhcp_config | bool
