---
# tasks file for ansible-kea-dhcp
- include_tasks:
    file: set_facts.yml
    apply:
      tags:
        - config
  tags:
    - config

- include_tasks: alpine.yml
  when: ansible_facts["os_family"] == "Alpine"

- include_tasks: debian.yml
  when: ansible_facts["os_family"] == "Debian"

- include_tasks: redhat.yml
  when: ansible_facts["os_family"] == "RedHat"

- include_tasks:
    file: config.yml
    apply:
      tags:
        - config
  when: kea_dhcp_config|bool
  tags:
    - config

- include_tasks: services.yml
