---
- name: services | Enabling Kea DHCP Services
  ansible.builtin.service:
    name: "{{ item['name'] }}"
    enabled: "{{ item['enabled'] }}"
  become: true
  loop: "{{ kea_dhcp_services }}"

- name: services | Ensuring Kea DHCP Services Are Started
  ansible.builtin.service:
    name: "{{ item['name'] }}"
    state: started
  become: true
  loop: "{{ kea_dhcp_services }}"
  when:
    - item['enabled'] | bool
