---
# handlers file for ansible-kea-dhcp
- name: Restart kea-dhcp
  ansible.builtin.service:
    name: "{{ item['name'] }}"
    state: restarted
  become: true
  loop: "{{ kea_dhcp_services }}"
  when:
    - item['enabled'] | bool
